# Generated by Django 2.1.15 on 2020-09-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_auto_20200917_2140'),
        ('accounts', '0002_remove_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='supplements.Functional'),
        ),
    ]
