# Generated by Django 2.1.15 on 2020-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200929_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='supplements.Category'),
        ),
    ]
