# Generated by Django 2.1.15 on 2020-10-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Functional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('limit_low', models.FloatField()),
                ('limit_high', models.FloatField()),
                ('precaution', models.TextField()),
                ('functionals', models.ManyToManyField(related_name='nutrients', to='supplements.Functional')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=50)),
                ('storage_method', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('product_form', models.CharField(max_length=50)),
                ('nutrients', models.ManyToManyField(related_name='supplements', to='supplements.Nutrient')),
            ],
        ),
    ]
