# Generated by Django 2.1.15 on 2020-09-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functional',
            old_name='catetory',
            new_name='category',
        ),
    ]
