# Generated by Django 2.1.15 on 2020-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_auto_20200917_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='functionals',
            field=models.ManyToManyField(related_name='nutrients', to='supplements.Functional'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='nutrients',
            field=models.ManyToManyField(related_name='supplements', to='supplements.Nutrient'),
        ),
    ]
