# Generated by Django 2.1.15 on 2020-09-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_auto_20200917_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='functional',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.Category'),
        ),
    ]
